= GameInfo API Docs
github.com()
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[Member-API]]
== Member

[[Member-회원가입]]
=== 회원가입
operation::member-signup[snippets='http-request,http-response,response-fields']

[[Member-조회]]
=== 조회
operation::member-get[snippets='http-request,http-response,request-parameters,response-fields']

[[Member-아이디-중복-조회]]
=== 아이디 중복 조회 (중복이면 true)
operation::member-duplicate[snippets='http-request,http-response']

[[Auth-API]]
== Auth

[[Auth-login]]
=== 로그인
operation::auth-login[snippets='http-request,http-response,response-fields']

[[Auth-logout]]
=== 로그아웃
operation::auth-logout[snippets='http-request,http-response']

[[Auth-reAuthorize]]
=== 권한 재인증 (토큰 재발급)
operation::auth-reaccess[snippets='http-request,http-response,response-headers']

[[Auth-getAuthority]]
=== 권한 확인 (Manager 이상)
operation::auth-getAuthority[snippets='http-request,http-response']


[[Genre-API]]
== Genre

[[Genre-create]]
=== 생성
operation::genre-create[snippets='http-request,http-response,response-fields']

[[Genre-update]]
=== 수정
operation::genre-update[snippets='http-request,http-response,request-fields,response-fields']

[[Genre-delete]]
=== 삭제
operation::genre-delete[snippets='http-request,http-response,request-fields']

[[Genre-list]]
=== 리스트 조회
operation::genre-list[snippets='http-request,http-response,request-parameters,response-fields']

[[Genre-search]]
=== 리스트 검색 조회
operation::genre-search[snippets='http-request,http-response,request-parameters,response-fields']


[[Platform-API]]
== Platform

[[Platform-create]]
=== 생성
operation::platform-create[snippets='http-request,http-response,request-fields,response-fields']

[[Platform-update]]
=== 수정
operation::platform-update[snippets='http-request,http-response,request-fields,response-fields']

[[Platform-delete]]
=== 삭제
operation::platform-delete[snippets='http-request,http-response,request-fields']

[[Platform-list]]
=== 리스트 조회
operation::platform-list[snippets='http-request,http-response,request-parameters,response-fields']

[[Platform-search]]
=== 리스트 검색 조회
operation::platform-search[snippets='http-request,http-response,request-parameters,response-fields']


[[Games-API]]
== Game

[[Games-create]]
=== 생성
operation::game-create[snippets='http-request,http-response,request-fields,response-fields']

[[Games-get]]
=== 조회
operation::games-get[snippets='http-request,http-response,response-fields']

[[Games-list]]
=== 리스트 조회
operation::games-list[snippets='http-request,http-response,request-parameters,response-fields']

[[Games-search]]
=== 리스트 검색 조회
operation::games-search[snippets='http-request,http-response,request-parameters,response-fields']


[[Post-API]]
== Post

[[Post-create]]
=== 생성
operation::post-create[snippets='http-request,http-response,request-fields,response-fields']

[[Post-update]]
=== 수정
operation::post-update[snippets='http-request,http-response,request-fields']

[[Post-delete]]
=== 삭제
operation::post-delete[snippets='http-request,http-response,request-parameters']

[[Post-get]]
=== 조회
operation::post-get[snippets='http-request,http-response,path-parameters,response-fields']

[[Post-list]]
=== 리스트 조회
operation::post-list[snipperts='http-request,http-response,request-params,response-fields']